## Importing librarys and data

In [583]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime

In [584]:
df = pd.read_csv("./src/data/Amazon Customer Behavior Survey.csv")

## Entendiendo el dataset

In [585]:
df

,Timestamp,age,Gender,Purchase_Frequency,Purchase_Categories,Personalized_Recommendation_Frequency,Browsing_Frequency,Product_Search_Method,Search_Result_Exploration,Customer_Reviews_Importance,...,Saveforlater_Frequency,Review_Left,Review_Reliability,Review_Helpfulness,Personalized_Recommendation_Frequency,Recommendation_Helpfulness,Rating_Accuracy,Shopping_Satisfaction,Service_Appreciation,Improvement_Areas
0,2023/06/04 1:28:19 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care,Yes,Few times a week,Keyword,Multiple pages,1,...,Sometimes,Yes,Occasionally,Yes,2,Yes,1,1,Competitive prices,Reducing packaging waste
1,2023/06/04 2:30:44 PM GMT+5:30,23,Female,Once a month,Clothing and Fashion,Yes,Few times a month,Keyword,Multiple pages,1,...,Rarely,No,Heavily,Yes,2,Sometimes,3,2,Wide product selection,Reducing packaging waste
2,2023/06/04 5:04:56 PM GMT+5:30,24,Prefer not to say,Few times a month,Groceries and Gourmet Food;Clothing and Fashion,No,Few times a month,Keyword,Multiple pages,2,...,Rarely,No,Occasionally,No,4,No,3,3,Competitive prices,Product quality and accuracy
3,2023/06/04 5:13:00 PM GMT+5:30,24,Female,Once a month,Beauty and Personal Care;Clothing and Fashion;...,Sometimes,Few times a month,Keyword,First page,5,...,Sometimes,Yes,Heavily,Yes,3,Sometimes,3,4,Competitive prices,Product quality and accuracy
4,2023/06/04 5:28:06 PM GMT+5:30,22,Female,Less than once a month,Beauty and Personal Care;Clothing and Fashion,Yes,Few times a month,Filter,Multiple pages,1,...,Rarely,No,Heavily,Yes,4,Yes,2,2,Competitive prices,Product quality and accuracy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597,2023/06/12 4:02:02 PM GMT+5:30,23,Female,Once a week,Beauty and Personal Care,Sometimes,Few times a week,categories,Multiple pages,4,...,Sometimes,Yes,Moderately,Sometimes,3,Sometimes,3,4,Competitive prices,Customer service responsiveness
598,2023/06/12 4:02:53 PM GMT+5:30,23,Female,Once a week,Clothing and Fashion,Sometimes,Few times a week,Filter,Multiple pages,3,...,Sometimes,Yes,Heavily,Sometimes,3,Sometimes,3,3,Product recommendations,Reducing packaging waste
599,2023/06/12 4:03:59 PM GMT+5:30,23,Female,Once a month,Beauty and Personal Care,Sometimes,Few times a week,categories,Multiple pages,3,...,Sometimes,Yes,Occasionally,Sometimes,3,Sometimes,2,3,Wide product selection,Product quality and accuracy
600,2023/06/12 9:57:20 PM GMT+5:30,23,Female,Few times a month,Beauty and Personal Care;Clothing and Fashion;...,Yes,Few times a month,Keyword,Multiple pages,1,...,Sometimes,No,Heavily,Yes,2,Yes,2,2,Wide product selection,Product quality and accuracy
601,2023/06/16 9:16:05 AM GMT+5:30,23,Female,Once a week,Clothing and Fashion,Sometimes,Multiple times a day,Keyword,Multiple pages,3,...,Sometimes,Yes,Moderately,Sometimes,3,Sometimes,3,3,Product recommendations,Product quality and accuracy

In [586]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 602 entries, 0 to 601
Data columns (total 23 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Timestamp                               602 non-null    str
 1   age                                     602 non-null    int64
 2   Gender                                  602 non-null    str
 3   Purchase_Frequency                      602 non-null    str
 4   Purchase_Categories                     602 non-null    str
 5   Personalized_Recommendation_Frequency   602 non-null    str
 6   Browsing_Frequency                      602 non-null    str
 7   Product_Search_Method                   600 non-null    str
 8   Search_Result_Exploration               602 non-null    str
 9   Customer_Reviews_Importance             602 non-null    int64
 10  Add_to_Cart_Browsing                    602 non-null    str
 11  Cart_Completion_Frequency               602 non-null    str
 12  Cart_Abandonment_Factors                602 non-null    str
 13  Saveforlater_Frequency                  602 non-null    str
 14  Review_Left                             602 non-null    str
 15  Review_Reliability                      602 non-null    str
 16  Review_Helpfulness                      602 non-null    str
 17  Personalized_Recommendation_Frequency   602 non-null    int64
 18  Recommendation_Helpfulness              602 non-null    str
 19  Rating_Accuracy                         602 non-null    int64
 20  Shopping_Satisfaction                   602 non-null    int64
 21  Service_Appreciation                    602 non-null    str
 22  Improvement_Areas                       602 non-null    str
dtypes: int64(5), str(18)
memory usage: 108.3 KB

El timestamp está como string y lo queremos en DataTime. Lo tenemos en cuenta para después.

In [587]:
df.columns

Index(['Timestamp', 'age', 'Gender', 'Purchase_Frequency',
       'Purchase_Categories', 'Personalized_Recommendation_Frequency',
       'Browsing_Frequency', 'Product_Search_Method',
       'Search_Result_Exploration', 'Customer_Reviews_Importance',
       'Add_to_Cart_Browsing', 'Cart_Completion_Frequency',
       'Cart_Abandonment_Factors', 'Saveforlater_Frequency', 'Review_Left',
       'Review_Reliability', 'Review_Helpfulness',
       'Personalized_Recommendation_Frequency ', 'Recommendation_Helpfulness',
       'Rating_Accuracy ', 'Shopping_Satisfaction', 'Service_Appreciation',
       'Improvement_Areas'],
      dtype='str')

In [588]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,602.0,30.790698,10.193276,3.0,23.0,26.0,36.0,67.0
Customer_Reviews_Importance,602.0,2.480066,1.185226,1.0,1.0,3.0,3.0,5.0
Personalized_Recommendation_Frequency,602.0,2.699336,1.042028,1.0,2.0,3.0,3.0,5.0
Rating_Accuracy,602.0,2.672757,0.899744,1.0,2.0,3.0,3.0,5.0
Shopping_Satisfaction,602.0,2.463455,1.012152,1.0,2.0,2.0,3.0,5.0

Vemos que Personalized_Recomendation_Frequency, Parting_Accuracy y Shopping_Satisfaction tienes casi los mismos valores y comparten como mínimo y máximo el mismo número. Deducimos que seguramente sea de una encuesta en la que les hayan hecho elegir del 1 al 5. Podemos asignarles valores en la visualización. Lo tenemos en cuenta para después.

In [589]:
df["Personalized_Recommendation_Frequency"].value_counts()

Personalized_Recommendation_Frequency
No           251
Sometimes    229
Yes          122
Name: count, dtype: int64

In [590]:
df["Personalized_Recommendation_Frequency "].value_counts()

Personalized_Recommendation_Frequency
3    240
2    169
1     80
4     78
5     35
Name: count, dtype: int64

Vemos que hay dos columnas con el mismo nombre pero con distintos. La primera se trata de si alguna vez has hecho una compra basandote en recomendaciones personalizadas de Amazon y la segunda que tan a menudo recibes recomendaciones personalizadas de Amazon. Lo tenemos en cuenta para después.

In [591]:
df.isnull().sum().sort_values(ascending=False)

Product_Search_Method                     2
age                                       0
Timestamp                                 0
Purchase_Frequency                        0
Purchase_Categories                       0
Personalized_Recommendation_Frequency     0
Gender                                    0
Browsing_Frequency                        0
Search_Result_Exploration                 0
Customer_Reviews_Importance               0
Add_to_Cart_Browsing                      0
Cart_Completion_Frequency                 0
Cart_Abandonment_Factors                  0
Saveforlater_Frequency                    0
Review_Left                               0
Review_Reliability                        0
Review_Helpfulness                        0
Personalized_Recommendation_Frequency     0
Recommendation_Helpfulness                0
Rating_Accuracy                           0
Shopping_Satisfaction                     0
Service_Appreciation                      0
Improvement_Areas                         0
dtype: int64

In [592]:
df["Product_Search_Method"].unique()

<StringArray>
['Keyword', 'Filter', 'categories', 'others', nan]
Length: 5, dtype: str

In [593]:
df[df["Product_Search_Method"].isna()]

,Timestamp,age,Gender,Purchase_Frequency,Purchase_Categories,Personalized_Recommendation_Frequency,Browsing_Frequency,Product_Search_Method,Search_Result_Exploration,Customer_Reviews_Importance,...,Saveforlater_Frequency,Review_Left,Review_Reliability,Review_Helpfulness,Personalized_Recommendation_Frequency,Recommendation_Helpfulness,Rating_Accuracy,Shopping_Satisfaction,Service_Appreciation,Improvement_Areas
119,2023/06/06 2:07:12 PM GMT+5:30,21,Female,Once a month,Clothing and Fashion,Sometimes,Few times a week,NaN,Multiple pages,3,...,Often,No,Moderately,Sometimes,3,Sometimes,3,3,User-friendly website/app interface,Customer service responsiveness
382,2023/06/08 5:49:59 PM GMT+5:30,47,Female,Few times a month,Beauty and Personal Care;Clothing and Fashion;...,No,Multiple times a day,NaN,Multiple pages,1,...,Often,No,Moderately,No,2,No,3,2,Wide product selection,Shipping speed and reliability

Vemos que en Product_Search_Method hay nulos. Lo tenemos en cuenta para después.

In [594]:
df.age.describe()

count    602.000000
mean      30.790698
std       10.193276
min        3.000000
25%       23.000000
50%       26.000000
75%       36.000000
max       67.000000
Name: age, dtype: float64

In [595]:
df["age"].value_counts().sort_index().head(6)

age
3     1
12    1
15    2
16    5
17    4
18    7
Name: count, dtype: int64

Vemos que hay menores haciendo compras. Lo tenemos en cuenta para después, expecialmente el de 3 años.

In [596]:
df.Purchase_Frequency.unique()

<StringArray>
[     'Few times a month',           'Once a month', 'Less than once a month',
  'Multiple times a week',            'Once a week']
Length: 5, dtype: str

In [597]:
df.nunique()

Timestamp                                 601
age                                        50
Gender                                      4
Purchase_Frequency                          5
Purchase_Categories                        29
Personalized_Recommendation_Frequency       3
Browsing_Frequency                          4
Product_Search_Method                       4
Search_Result_Exploration                   2
Customer_Reviews_Importance                 5
Add_to_Cart_Browsing                        3
Cart_Completion_Frequency                   5
Cart_Abandonment_Factors                    4
Saveforlater_Frequency                      5
Review_Left                                 2
Review_Reliability                          5
Review_Helpfulness                          3
Personalized_Recommendation_Frequency       5
Recommendation_Helpfulness                  3
Rating_Accuracy                             5
Shopping_Satisfaction                       5
Service_Appreciation                        9
Improvement_Areas                          18
dtype: int64

In [598]:
df["Purchase_Categories"].value_counts()

Purchase_Categories
Beauty and Personal Care                                                                            106
Clothing and Fashion                                                                                106
others                                                                                               48
Beauty and Personal Care;Clothing and Fashion                                                        46
Beauty and Personal Care;Clothing and Fashion;Home and Kitchen                                       42
Groceries and Gourmet Food;Beauty and Personal Care;Clothing and Fashion;Home and Kitchen;others     32
Clothing and Fashion;Home and Kitchen                                                                27
Home and Kitchen                                                                                     24
Beauty and Personal Care;Home and Kitchen                                                            21
Clothing and Fashion;Home and Kitchen;others                                                         16
Clothing and Fashion;others                                                                          14
Groceries and Gourmet Food                                                                           14
Groceries and Gourmet Food;Beauty and Personal Care;Clothing and Fashion;Home and Kitchen            14
Beauty and Personal Care;Clothing and Fashion;others                                                 12
Groceries and Gourmet Food;Beauty and Personal Care;Clothing and Fashion                             10
Home and Kitchen;others                                                                               9
Beauty and Personal Care;Clothing and Fashion;Home and Kitchen;others                                 8
Beauty and Personal Care;others                                                                       7
Groceries and Gourmet Food;Beauty and Personal Care                                                   7
Groceries and Gourmet Food;Clothing and Fashion                                                       6
Groceries and Gourmet Food;Home and Kitchen;others                                                    6
Beauty and Personal Care;Home and Kitchen;others                                                      5
Groceries and Gourmet Food;Home and Kitchen                                                           5
Groceries and Gourmet Food;Beauty and Personal Care;Home and Kitchen                                  4
Groceries and Gourmet Food;Clothing and Fashion;Home and Kitchen                                      4
Groceries and Gourmet Food;Clothing and Fashion;Home and Kitchen;others                               3
Groceries and Gourmet Food;Beauty and Personal Care;others                                            3
Groceries and Gourmet Food;Clothing and Fashion;others                                                2
Groceries and Gourmet Food;Beauty and Personal Care;Clothing and Fashion;others                       1
Name: count, dtype: int64

Nos preguntamos si podriamos encapsular algunas categorias o crear una nueva columna para una observación más exaustiva. Lo tenemos en cuenta para después.

##### Significado columnas

1. age = edad  
2. gender = género  
3. Purchase_Frequency = ¿Con qué frecuencia realizas compras en Amazon?  
4. Purchase_Categories = ¿Qué categorías de productos sueles comprar en Amazon?  
5. Personalized_Recommendation_Frequency = ¿Alguna vez has comprado un producto basándote en recomendaciones personalizadas de Amazon?  
6. Browsing_Frequency = ¿Con qué frecuencia navegas por el sitio web o la aplicación de Amazon?  
7. Product_Search_Method = ¿Cómo buscas productos en Amazon?  
8. Search_Result_Exploration = ¿Sueles explorar varias páginas de resultados de búsqueda o te quedas en la primera página?  
9. Customer_Reviews_Importance = ¿Qué importancia tienen las reseñas de clientes en tu proceso de toma de decisiones?  
10. Add_to_Cart_Browsing = ¿Añades productos a tu carrito mientras navegas por Amazon?  
11. Cart_Completion_Frequency = ¿Con qué frecuencia completas la compra después de añadir productos al carrito?  
12. Cart_Abandonment_Factors = ¿Qué factores influyen en tu decisión de abandonar una compra en el carrito?  
13. Saveforlater_Frequency = ¿Utilizas la función “Guardar para más tarde” de Amazon y, si es así, con qué frecuencia?  
14. Review_Left = ¿Alguna vez has dejado una reseña de un producto en Amazon?  
15. Review_Reliability = ¿Cuánto confías en las reseñas de productos al realizar una compra?  
16. Review_Helpfulness = ¿Encuentras información útil en las reseñas de otros clientes?  
17. Personalized_Recommendation_Frequency = ¿Con qué frecuencia recibes recomendaciones personalizadas de productos de Amazon?  
18. Recommendation_Helpfulness = ¿Te resultan útiles las recomendaciones?  
19. Rating_Accuracy = ¿Cómo calificarías la relevancia y precisión de las recomendaciones que recibes?  
20. Shopping_Satisfaction = ¿Qué tan satisfecho estás con tu experiencia general de compra en Amazon?  
21. Service_Appreciation = ¿Qué aspectos de los servicios de Amazon aprecias más?  
22. Improvement_Areas = ¿Hay áreas en las que crees que Amazon puede mejorar?

In [599]:
for col in df.columns:
    print(f"{col}:",df[col].unique())

Timestamp: <StringArray>
['2023/06/04 1:28:19 PM GMT+5:30', '2023/06/04 2:30:44 PM GMT+5:30',
 '2023/06/04 5:04:56 PM GMT+5:30', '2023/06/04 5:13:00 PM GMT+5:30',
 '2023/06/04 5:28:06 PM GMT+5:30', '2023/06/04 6:01:59 PM GMT+5:30',
 '2023/06/04 6:31:41 PM GMT+5:30', '2023/06/04 7:13:12 PM GMT+5:30',
 '2023/06/04 7:23:21 PM GMT+5:30', '2023/06/04 7:33:12 PM GMT+5:30',
 ...
 '2023/06/12 3:56:57 PM GMT+5:30', '2023/06/12 3:57:52 PM GMT+5:30',
 '2023/06/12 3:59:10 PM GMT+5:30', '2023/06/12 3:59:59 PM GMT+5:30',
 '2023/06/12 4:00:56 PM GMT+5:30', '2023/06/12 4:02:02 PM GMT+5:30',
 '2023/06/12 4:02:53 PM GMT+5:30', '2023/06/12 4:03:59 PM GMT+5:30',
 '2023/06/12 9:57:20 PM GMT+5:30', '2023/06/16 9:16:05 AM GMT+5:30']
Length: 601, dtype: str
age: [23 24 22 21 20 25 16 64 29 19 26 32 30 40 36 31 47 54 58 53 28 55 62 27
 34 44 38 35 42 37 45 50 63 46 33 60 18 17 57 41 39 48 49 15 43 52  3 67
 56 12]
Gender: <StringArray>
['Female', 'Prefer not to say', 'Male', 'Others']
Length: 4, dtype: str
Purchase_Frequency: <StringArray>
[     'Few times a month',           'Once a month', 'Less than once a month',
  'Multiple times a week',            'Once a week']
Length: 5, dtype: str
Purchase_Categories: <StringArray>
[                                                                        'Beauty and Personal Care',
                                                                             'Clothing and Fashion',
                                                  'Groceries and Gourmet Food;Clothing and Fashion',
                                             'Beauty and Personal Care;Clothing and Fashion;others',
                                                    'Beauty and Personal Care;Clothing and Fashion',
                                   'Beauty and Personal Care;Clothing and Fashion;Home and Kitchen',
                                                            'Clothing and Fashion;Home and Kitchen',
                                                                                           'others',
                                                                      'Clothing and Fashion;others',
                                                        'Beauty and Personal Care;Home and Kitchen',
                                                                       'Groceries and Gourmet Food',
                                           'Groceries and Gourmet Food;Clothing and Fashion;others',
        'Groceries and Gourmet Food;Beauty and Personal Care;Clothing and Fashion;Home and Kitchen',
 'Groceries and Gourmet Food;Beauty and Personal Care;Clothing and Fashion;Home and Kitchen;others',
                                                                                 'Home and Kitchen',
                                                                  'Beauty and Personal Care;others',
                                                 'Beauty and Personal Care;Home and Kitchen;others',
                                                                          'Home and Kitchen;others',
                                                      'Groceries and Gourmet Food;Home and Kitchen',
                            'Beauty and Personal Care;Clothing and Fashion;Home and Kitchen;others',
                             'Groceries and Gourmet Food;Beauty and Personal Care;Home and Kitchen',
                                               'Groceries and Gourmet Food;Home and Kitchen;others',
                          'Groceries and Gourmet Food;Clothing and Fashion;Home and Kitchen;others',
                                              'Groceries and Gourmet Food;Beauty and Personal Care',
                                                     'Clothing and Fashion;Home and Kitchen;others',
                         'Groceries and Gourmet Food;Beauty and Personal Care;Clothing and Fashion',
                                 'Groceries and Gourmet Food;Clothing and Fashion;Home and Kitchen',
                                       'Groceries and Gourmet Food;Beauty and Personal Care;others',
                  'Groceries and Gourmet Food;Beauty and Personal Care;Clothing and Fashion;others']
Length: 29, dtype: str
Personalized_Recommendation_Frequency: <StringArray>
['Yes', 'No', 'Sometimes']
Length: 3, dtype: str
Browsing_Frequency: <StringArray>
['Few times a week', 'Few times a month', 'Rarely', 'Multiple times a day']
Length: 4, dtype: str
Product_Search_Method: <StringArray>
['Keyword', 'Filter', 'categories', 'others', nan]
Length: 5, dtype: str
Search_Result_Exploration: <StringArray>
['Multiple pages', 'First page']
Length: 2, dtype: str
Customer_Reviews_Importance: [1 2 5 3 4]
Add_to_Cart_Browsing: <StringArray>
['Yes', 'Maybe', 'No']
Length: 3, dtype: str
Cart_Completion_Frequency: <StringArray>
['Sometimes', 'Often', 'Rarely', 'Never', 'Always']
Length: 5, dtype: str
Cart_Abandonment_Factors: <StringArray>
[            'Found a better price elsewhere',
                        'High shipping costs',
 'Changed my mind or no longer need the item',
                                     'others']
Length: 4, dtype: str
Saveforlater_Frequency: <StringArray>
['Sometimes', 'Rarely', 'Never', 'Often', 'Always']
Length: 5, dtype: str
Review_Left: <StringArray>
['Yes', 'No']
Length: 2, dtype: str
Review_Reliability: <StringArray>
['Occasionally', 'Heavily', 'Moderately', 'Never', 'Rarely']
Length: 5, dtype: str
Review_Helpfulness: <StringArray>
['Yes', 'No', 'Sometimes']
Length: 3, dtype: str
Personalized_Recommendation_Frequency : [2 4 3 5 1]
Recommendation_Helpfulness: <StringArray>
['Yes', 'Sometimes', 'No']
Length: 3, dtype: str
Rating_Accuracy : [1 3 2 5 4]
Shopping_Satisfaction: [1 2 3 4 5]
Service_Appreciation: <StringArray>
[                 'Competitive prices',              'Wide product selection',
 'User-friendly website/app interface',                                   '.',
                   'Customer service ',             'Product recommendations',
                    'Customer service',                      'Quick delivery',
                       'All the above']
Length: 9, dtype: str
Improvement_Areas: <StringArray>
[                                                      'Reducing packaging waste',
                                                   'Product quality and accuracy',
                                                 'Shipping speed and reliability',
                                                'Customer service responsiveness',
                                                                              '.',
                                                                        'Nothing',
                                'better app interface and lower shipping charges',
                                                                            'Nil',
                                           'Add more familiar brands to the list',
                                                                             'UI',
                  'Scrolling option would be much better than going to next page',
                    'Quality of product is very poor according to the big offers',
 'I have no problem with Amazon yet. But others tell me about the refund issues ',
                                                                'User interface ',
                                                 'Irrelevant product suggestions',
                                                          'User interface of app',
                                           'I don't have any problem with Amazon',
                                                        'No problems with Amazon']
Length: 18, dtype: str

Fijarnos en el Search_Result_Exploration nos podria dar indicios de compraciones de precio o duda a la hora de comprar. Lo tenemos en cuenta para después.

Vemos resultados repetidos o incoherentes en Service_Appreciation. Lo tenemos en cuenta para después.

Vemos resultados repetidos, con espacios a final o incoherentes en Improvement_Areas. Lo tenemos en cuenta para después.

In [600]:
df.loc[df["Improvement_Areas"].isin(["UI", "Nil","Nothing"])]

,Timestamp,age,Gender,Purchase_Frequency,Purchase_Categories,Personalized_Recommendation_Frequency,Browsing_Frequency,Product_Search_Method,Search_Result_Exploration,Customer_Reviews_Importance,...,Saveforlater_Frequency,Review_Left,Review_Reliability,Review_Helpfulness,Personalized_Recommendation_Frequency,Recommendation_Helpfulness,Rating_Accuracy,Shopping_Satisfaction,Service_Appreciation,Improvement_Areas
41,2023/06/05 12:36:02 AM GMT+5:30,32,Male,Less than once a month,others,No,Rarely,Keyword,First page,1,...,Never,No,Moderately,Yes,1,No,4,1,Customer service,Nothing
156,2023/06/06 7:10:55 PM GMT+5:30,24,Male,Less than once a month,others,No,Few times a month,Keyword,Multiple pages,4,...,Sometimes,No,Occasionally,Yes,3,Yes,4,5,Wide product selection,Nil
190,2023/06/07 6:09:58 AM GMT+5:30,23,Male,Once a month,Clothing and Fashion;others,No,Few times a month,Keyword,Multiple pages,1,...,Often,Yes,Heavily,Yes,3,No,3,3,Competitive prices,UI

Ya que son pocas columnas pensamos en cambiar los valores abstractos a "Nothing" ya que así manejaremos mejor los datos.

In [601]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Timestamp,602,601,2023/06/07 11:47:44 AM GMT+5:30,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,602.0,NaN,NaN,NaN,30.790698,10.193276,3.0,23.0,26.0,36.0,67.0
Gender,602,4,Female,352,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Purchase_Frequency,602,5,Few times a month,203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Purchase_Categories,602,29,Beauty and Personal Care,106,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Personalized_Recommendation_Frequency,602,3,No,251,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Browsing_Frequency,602,4,Few times a week,249,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product_Search_Method,600,4,categories,223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Search_Result_Exploration,602,2,Multiple pages,442,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer_Reviews_Importance,602.0,NaN,NaN,NaN,2.480066,1.185226,1.0,1.0,3.0,3.0,5.0
Add_to_Cart_Browsing,602,3,Maybe,248,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cart_Completion_Frequency,602,5,Sometimes,304,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cart_Abandonment_Factors,602,4,Found a better price elsewhere,255,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Saveforlater_Frequency,602,5,Sometimes,251,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Review_Left,602,2,Yes,310,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Review_Reliability,602,5,Moderately,199,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Review_Helpfulness,602,3,Yes,237,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Personalized_Recommendation_Frequency,602.0,NaN,NaN,NaN,2.699336,1.042028,1.0,2.0,3.0,3.0,5.0
Recommendation_Helpfulness,602,3,Sometimes,273,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rating_Accuracy,602.0,NaN,NaN,NaN,2.672757,0.899744,1.0,2.0,3.0,3.0,5.0
Shopping_Satisfaction,602.0,NaN,NaN,NaN,2.463455,1.012152,1.0,2.0,2.0,3.0,5.0
Service_Appreciation,602,9,Product recommendations,185,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Improvement_Areas,602,18,Customer service responsiveness,217,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [602]:
df.duplicated().sum()

np.int64(0)

In [603]:
df["Timestamp"].duplicated().sum()

np.int64(1)

In [604]:
df["Timestamp"].value_counts(ascending=False)

Timestamp
2023/06/07 11:47:44 AM GMT+5:30    2
2023/06/04 1:28:19 PM GMT+5:30     1
2023/06/04 2:30:44 PM GMT+5:30     1
2023/06/04 5:04:56 PM GMT+5:30     1
2023/06/04 5:13:00 PM GMT+5:30     1
                                  ..
2023/06/12 4:02:02 PM GMT+5:30     1
2023/06/12 4:02:53 PM GMT+5:30     1
2023/06/12 4:03:59 PM GMT+5:30     1
2023/06/12 9:57:20 PM GMT+5:30     1
2023/06/16 9:16:05 AM GMT+5:30     1
Name: count, Length: 601, dtype: int64

In [605]:
df[df["Timestamp"].isin(["2023/06/07 11:47:44 AM GMT+5:30"])]

,Timestamp,age,Gender,Purchase_Frequency,Purchase_Categories,Personalized_Recommendation_Frequency,Browsing_Frequency,Product_Search_Method,Search_Result_Exploration,Customer_Reviews_Importance,...,Saveforlater_Frequency,Review_Left,Review_Reliability,Review_Helpfulness,Personalized_Recommendation_Frequency,Recommendation_Helpfulness,Rating_Accuracy,Shopping_Satisfaction,Service_Appreciation,Improvement_Areas
205,2023/06/07 11:47:44 AM GMT+5:30,40,Female,Less than once a month,Home and Kitchen,Sometimes,Rarely,categories,Multiple pages,3,...,Rarely,No,Moderately,Yes,3,Yes,2,2,Wide product selection,Customer service responsiveness
206,2023/06/07 11:47:44 AM GMT+5:30,41,Male,Less than once a month,Clothing and Fashion,Sometimes,Few times a month,Keyword,Multiple pages,1,...,Rarely,Yes,Rarely,Yes,5,Yes,2,3,Wide product selection,Shipping speed and reliability

Vemos que se hicieron a la misma hora pero son independientes. Descartamos la posibilidad de duplicados.

Finalmente creamos un diccionario para verlo mas fácil y rápido.

In [606]:
# Genera un data dictionary automático

# Dividimos los tipos según el tipo de analisis que haremos a continuación
def var_type(col):
    if pd.api.types.is_numeric_dtype(df[col]):
        return "numérica"
    elif pd.api.types.is_datetime64_any_dtype(df[col]):
        return "fecha"
    else:
        return "categórica"

data_dict = pd.DataFrame({
    'columna': df.columns,
    'tipo': [var_type(c) for c in df.columns],
    'dtype': df.dtypes.astype(str).values,
    'nulos_pct': (df.isnull().sum()),
    'unicos': df.nunique().values,
    'min': [df[c].min() if pd.api.types.is_numeric_dtype(df[c]) else None for c in df.columns],
    'max': [df[c].max() if pd.api.types.is_numeric_dtype(df[c]) else None for c in df.columns],
    'duplicados': [df[c].duplicated().sum() for c in df.columns]})
data_dict.to_csv('data_dictionary.csv', index=False)
data_dict

,columna,tipo,dtype,nulos_pct,unicos,min,max,duplicados
Timestamp,Timestamp,categórica,str,0,601,NaN,NaN,1
age,age,numérica,int64,0,50,3.0,67.0,552
Gender,Gender,categórica,str,0,4,NaN,NaN,598
Purchase_Frequency,Purchase_Frequency,categórica,str,0,5,NaN,NaN,597
Purchase_Categories,Purchase_Categories,categórica,str,0,29,NaN,NaN,573
Personalized_Recommendation_Frequency,Personalized_Recommendation_Frequency,categórica,str,0,3,NaN,NaN,599
Browsing_Frequency,Browsing_Frequency,categórica,str,0,4,NaN,NaN,598
Product_Search_Method,Product_Search_Method,categórica,str,2,4,NaN,NaN,597
Search_Result_Exploration,Search_Result_Exploration,categórica,str,0,2,NaN,NaN,600
Customer_Reviews_Importance,Customer_Reviews_Importance,numérica,int64,0,5,1.0,5.0,597
Add_to_Cart_Browsing,Add_to_Cart_Browsing,categórica,str,0,3,NaN,NaN,599
Cart_Completion_Frequency,Cart_Completion_Frequency,categórica,str,0,5,NaN,NaN,597
Cart_Abandonment_Factors,Cart_Abandonment_Factors,categórica,str,0,4,NaN,NaN,598
Saveforlater_Frequency,Saveforlater_Frequency,categórica,str,0,5,NaN,NaN,597
Review_Left,Review_Left,categórica,str,0,2,NaN,NaN,600
Review_Reliability,Review_Reliability,categórica,str,0,5,NaN,NaN,597
Review_Helpfulness,Review_Helpfulness,categórica,str,0,3,NaN,NaN,599
Personalized_Recommendation_Frequency,Personalized_Recommendation_Frequency,numérica,int64,0,5,1.0,5.0,597
Recommendation_Helpfulness,Recommendation_Helpfulness,categórica,str,0,3,NaN,NaN,599
Rating_Accuracy,Rating_Accuracy,numérica,int64,0,5,1.0,5.0,597
Shopping_Satisfaction,Shopping_Satisfaction,numérica,int64,0,5,1.0,5.0,597
Service_Appreciation,Service_Appreciation,categórica,str,0,9,NaN,NaN,593
Improvement_Areas,Improvement_Areas,categórica,str,0,18,NaN,NaN,584

## Limpieza dataset

In [607]:
# Convertir fechas en datetime
df["Timestamp"] = pd.to_datetime(df["Timestamp"], format="%Y/%m/%d %I:%M:%S %p GMT+5:30")

In [608]:
# Limpiamos los nulos de Product_Search_Method transformandolos en la moda
df["Product_Search_Method"] = df["Product_Search_Method"].fillna(df["Product_Search_Method"].mode()[0])

In [609]:
# Reasignamos otro nombre a la columna Personalized_Recommendation_Frequency 
df.rename(columns={"Personalized_Recommendation_Frequency": "Purchase_Based_on_Recommendations"}, inplace=True)

# Corregimos la columna Personalized_Recommendation_Frequency con espacio al final
df.rename(columns={"Personalized_Recommendation_Frequency ": "Personalized_Recommendation_Frequency"}, inplace=True)

In [610]:
# Corregimos respuestas de Service_Appreciation quitando problemas de escritura y convirtiendo la . en la moda

df["Service_Appreciation"] = df["Service_Appreciation"].str.strip().str.capitalize().replace(".", df.Service_Appreciation.mode()[0])

In [611]:
# Corregimos respuestas de Improvement_Areas quitando problemas de escritura y convirtiendo a "Nothing" los datos incoherentes

df["Improvement_Areas"] = df["Improvement_Areas"].str.strip().str.capitalize().replace([".","Ui", "Nil"], "Nothing")

In [ ]:
# Encodeamos ciertas columnas ya que mantienen un orden

ordinal_cols = {
    "Purchase_Frequency": ["Less than once a month", "Once a month", "Few times a month", "Once a week", "Multiple times a week"],
    "Browsing_Frequency": ["Rarely", "Few times a month", "Few times a week", "Multiple times a day"],
    "Cart_Completion_Frequency": ["Never", "Rarely", "Sometimes", "Often", "Always"],
    "Saveforlater_Frequency": ["Never", "Rarely", "Sometimes", "Often", "Always"],
    "Purchase_Based_on_Recommendations": ["No", "Sometimes", "Yes"],
}

for col, order in ordinal_cols.items():
    df[col + "_enc"] = df[col].map({v: i+1 for i, v in enumerate(order)})

In [613]:
df.isnull().sum().sort_values(ascending=False)

Timestamp                                0
age                                      0
Gender                                   0
Purchase_Frequency                       0
Purchase_Categories                      0
Purchase_Based_on_Recommendations        0
Browsing_Frequency                       0
Product_Search_Method                    0
Search_Result_Exploration                0
Customer_Reviews_Importance              0
Add_to_Cart_Browsing                     0
Cart_Completion_Frequency                0
Cart_Abandonment_Factors                 0
Saveforlater_Frequency                   0
Review_Left                              0
Review_Reliability                       0
Review_Helpfulness                       0
Personalized_Recommendation_Frequency    0
Recommendation_Helpfulness               0
Rating_Accuracy                          0
Shopping_Satisfaction                    0
Service_Appreciation                     0
Improvement_Areas                        0
Purchase_Frequency_enc                   0
Browsing_Frequency_enc                   0
Cart_Completion_Frequency_enc            0
Saveforlater_Frequency_enc               0
Purchase_Based_on_Recommendations_enc    0
dtype: int64

In [614]:
# Hacemos un binning en la edad/age

df["tramo_edad"] = pd.cut(df["age"],bins=[0, 17, 25, 35, 50, 65, 100],labels=['0-17','18-25', '26-35', '36-50', '51-65', '65+'])

In [644]:
df["tramo_edad"].value_counts().sort_index()

tramo_edad
0-17      13
18-25    262
26-35    168
36-50    130
51-65     27
65+        2
Name: count, dtype: int64

## Analysis

#### Analysis univariante

##### Númericas

In [616]:
[col for col in df.columns if var_type(col) == "numérica"]

['age',
 'Customer_Reviews_Importance',
 'Personalized_Recommendation_Frequency',
 'Rating_Accuracy ',
 'Shopping_Satisfaction',
 'Purchase_Frequency_enc',
 'Browsing_Frequency_enc',
 'Cart_Completion_Frequency_enc',
 'Saveforlater_Frequency_enc',
 'Purchase_Based_on_Recommendations_enc']

#### Categóricas

In [617]:
[col for col in df.columns if var_type(col) == "categórica"]

['Gender',
 'Purchase_Frequency',
 'Purchase_Categories',
 'Purchase_Based_on_Recommendations',
 'Browsing_Frequency',
 'Product_Search_Method',
 'Search_Result_Exploration',
 'Add_to_Cart_Browsing',
 'Cart_Completion_Frequency',
 'Cart_Abandonment_Factors',
 'Saveforlater_Frequency',
 'Review_Left',
 'Review_Reliability',
 'Review_Helpfulness',
 'Recommendation_Helpfulness',
 'Service_Appreciation',
 'Improvement_Areas',
 'tramo_edad']

#### Analysis bivariante

#### Analysis multivariante

## Hipotesis